### ISSUE TITLE
Event Update requires NAME.

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-api-events#52]
should name really be required to make any update on an event? Need to look closer at the schema and update accordingly.

**Comment by brettski** [comment]
This is not what I am experiencing with event's update mutation. I was able to update the description of an event with no reference to 'name'.

Though one issue I am seeing is that only the updated field is returned non-null in the Event type returned from the mutation

**Comment by brettski** [comment]
Looking at this [line](https://github.com/ThatConference/that-api-events/blob/86e5a167cc87ce710a28a99218a0705bc7bb87d9/src/dataSources/cloudFirestore/event.js#L57) we are returning the input which was provided to the update function not the result of the update

**Comment by brettski** [comment]
Not an issue.
