### ISSUE TITLE
query sessions by from date, doesn't appear to be returning starting day.

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-api-events#73]
To be honest, not entirely sure what is really going on. When trying to query 

```
query GetEventsSessions ($eventId: ID!, $onOrAfter: Date, $daysAfter: Int) {
    events {
      event(id: $eventId) {
        get {
          sessions(onOrAfter: $onOrAfter, daysAfter: $daysAfter) {
            ...coreFields
            speakers {
              id
              firstName
              lastName
              bio
              jobTitle
              company
              profileImage
              profileSlug
              earnedMeritBadges {
                id
                name
                image
                description
              }
            }
          }
        }
      }
    }
  }
```

Right now the onOrAfter date doesn't appear to be returning the sessions that were scheduled for today. The code looks correct so I'm guessing it's more of a timezone issue maybe since it appears to respect time, not just day. 

https://github.com/ThatConference/that.us/issues/287 ( right now is subtracting a day to work around it )

**Comment by brettski** [comment]
Close this is if it actually not an issue. If it is, please include `...coreFields` @csell5

**Comment by csell5** [comment]
yup. resolved on the front end.
